name: jonathan.davis
favicon: null
layout_spectrum: 0.25086
typography_spectrum: 0.3836414541583508
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#279a01'
    - '#d2e4a6'
    - '#13420c'
    - '#f1081b'
    - '#0103f4'
  brandStrength: 0.75
  lightness: 0.25
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
