name: jonathan.davis
favicon: null
layout_spectrum: 0.7503579151816666
typography_spectrum: 0.3836414541583508
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#3a3934'
    - '#888886'
    - '#83211f'
    - '#f0f0ee'
  brandStrength: 0.4375
  lightness: 0.25
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
